### ISSUE TITLE
Installation instructions in README

### ISSUE THREAD

**Issue by fabiantheblind** [titoBouzout/Dictionaries#34]
Great collection. Thank you. It could use some installation instructions.  

 install via:   

    git clone git@github.com:titoBouzout/Dictionaries.git /Users/[YOU USER NAME]/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Dictionaries  

Set the dictionary via:

    View>Dictionary>User>Dictionaries>German  

Toggle spellceck with F6  

Or something like this.

**Comment by titoBouzout** [comment]
Hi thanks! Not everyone use OSX and people should use Package Control to install this or any other pacakge.

**Comment by fabiantheblind** [comment]
Yes. Package Control would be better. It was just a suggestion. When I found this repo I asked me: "How to install this?"

**Comment by fabiantheblind** [comment]
Oh. Didn't get that [it is already in package control](https://packagecontrol.io/packages/Dictionaries). :-) Sorry.

**Comment by synox** [comment]
There should a header "Installation" and there a link to package control. It is not obvious that it is available there.
