### ISSUE TITLE
Use directories

### ISSUE THREAD

**Issue by adius** [titoBouzout/Dictionaries#37]
I think you should create a directory for each (main) language (e.g. english) with sub-directories for local dialects (canada,australia, …).
This would make this repo much cleaner!

Would you accept a pull request?

**Comment by titoBouzout** [comment]
I disagree, not all language will have subfolders, and creating a folder three files isn't looking good to me.

**Comment by titoBouzout** [comment]
Thanks for the idea anyways

**Comment by adius** [comment]
Well … that's unfortunate. I hate when I have to fork repos ^^
