### ISSUE TITLE
Dictionary names in each original language

### ISSUE THREAD

**Issue by megadr01d** [titoBouzout/Dictionaries#39]
@titoBouzout I've renamed all dictionary files to their original languages, eg. Français, Español, etc. I think it's more relevant this way for foreign users instead of using English for all languages. Anyway, I'm not sure about the common approach for dictionary names, are you interested in the renamed language list?

**Comment by megadr01d** [comment]
Just now, I noticed most are already translated [here](https://github.com/titoBouzout/Dictionaries#language-list) so the current English names must be the common approach. Sorry for the noise. Closing.

**Comment by titoBouzout** [comment]
Thanks, I also appreciate the language names in their original language, but I choose to put it english because unicode names may causes issues in some platform/installations

**Comment by megadr01d** [comment]
Absolutely, I see your point. Then, I'll make a pull request for the `readme.md#Language List` to update just the missing ones, later. Thanks.
