### ISSUE TITLE
Add this as a package

### ISSUE THREAD

**Issue by jaimejim** [titoBouzout/Dictionaries#44]
I think this feature should be added as a package so that it could be installed in a more automated fashion, for example fetching them from OOffice or adding a new repo just for that. 

(Wishful thinking I know...)

**Comment by titoBouzout** [comment]
these files need formatting, and reorganization, and is not that we have 10000000 languages in the world, so is smooth. We can keep it this way, and for installing you can just use package control  Thanks!
