### ISSUE TITLE
Removed from package control

### ISSUE THREAD

**Issue by prayoholic** [titoBouzout/Dictionaries#58]
This package appears to be removed from "Package Control"¨, is this permanent and what are the reason behind?
This is by far the most complete language package.

**Comment by titoBouzout** [comment]
https://github.com/titoBouzout/SideBarEnhancements/issues/327#issuecomment-247087166

**Comment by ljacqu** [comment]
NB: Link 404's as issues have been disabled for that repository in the meantime, it appears.

**Comment by MattDMo** [comment]
@ljacqu if you drop the link into Google, then click on the (small) downward arrow to the right of the result URL, you'll see an option for the cached page.

https://webcache.googleusercontent.com/search?q=cache:1RoFrFm6ph0J:https://github.com/titoBouzout/SideBarEnhancements/issues/327#issuecomment-247087166
